Repository opensearch-project/automation-app, pull requests merged in 2025-07, with the labels that each got.

#68 Add ollama integration in label-by-keyword call and test cases
  .github/workflows/build-test.yml
  .github/workflows/yaml-lint.yml
  .yamllint
  README.md
  configs/operations/add-labels-to-issues-prs-os-repo.yml
  package-lock.json
  package.json
  src/call/label-by-keyword.ts
  src/utility/llm/ollama-client.ts
  test/call/label-by-keyword.test.ts
  test/utility/llm/ollama-client.test.ts
Labels: enhancement, AI

#70 Improve call print-to-console test case coverage
  package-lock.json
  package.json
  src/utility/opensearch/opensearch-client.ts
  test/call/print-to-console.test.ts
  tsconfig.json
Labels: enhancement, first-time-contributor

#69 Add bedrock integration in label-by-keyword call and test cases
  configs/operations/add-labels-to-issues-prs-os-repo.yml
  package-lock.json
  package.json
  src/call/label-by-keyword.ts
  src/utility/llm/bedrock-client.ts
  src/utility/opensearch/opensearch-client.ts
  test/call/label-by-keyword.test.ts
  test/utility/llm/bedrock-client.test.ts
  tsconfig.json
Labels: enhancement, AI

#71 Add default region as us-east-1 to bedrock client
  README.md
  package-lock.json
  package.json
  src/utility/llm/bedrock-client.ts
Labels: enhancement, AI, seasoned-contributor
